// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-IIlX-yGYVrnl9tsktHDkLiEtfiBq4mQ',
    appId: '1:794494904809:web:83ea5ff3b0f62f1e0cc378',
    messagingSenderId: '794494904809',
    projectId: 'onlyjob-13c80',
    authDomain: 'onlyjob-13c80.firebaseapp.com',
    storageBucket: 'onlyjob-13c80.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnHyRy2Sbyk6-gdMzZjvOsEkORyR3jQg4',
    appId: '1:794494904809:android:e72f1f8ec5684fae0cc378',
    messagingSenderId: '794494904809',
    projectId: 'onlyjob-13c80',
    storageBucket: 'onlyjob-13c80.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPDuw2im1mZ-2SRxouvt55Jc-tBxiDa4c',
    appId: '1:794494904809:ios:bcb8b0a991e231e40cc378',
    messagingSenderId: '794494904809',
    projectId: 'onlyjob-13c80',
    storageBucket: 'onlyjob-13c80.appspot.com',
    iosBundleId: 'com.3L1J.onlyJob',
  );
}
